import type { CSSProperties } from 'react';
import type { Palette } from './themes';

export type Styles = Record<string, CSSProperties>;

export const makeStyles = (p: Palette): Styles => ({
  wrap: {
    minHeight: '100vh',
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'flex-start',
    justifyContent: 'center',
    gap: 24,
    padding: 16,
    boxSizing: 'border-box',
    background: p.pageBg,
    color: p.keyText,
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Consolas, monospace',
  },
  sidePanel: {
    width: '100%',
    maxWidth: 260,
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
    marginTop: 8,
  },
  sidePanelTitle: {
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: 3,
    textAlign: 'center',
    color: p.keyText,
    opacity: 0.85,
  },
  shell: {
    width: '100%',
    maxWidth: 360,
    background: `linear-gradient(180deg, ${p.shellLight} 0%, ${p.shell} 35%, ${p.shellDark} 100%)`,
    borderRadius: 38,
    padding: '20px 18px 26px',
    boxShadow: [
      '0 18px 40px rgba(0,0,0,0.55)',
      'inset 0 2px 0 rgba(255,255,255,0.08)',
      'inset 0 -2px 0 rgba(0,0,0,0.4)',
      'inset 0 0 0 2px #0a0d14',
    ].join(', '),
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
    position: 'relative',
  },
  brandBar: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '2px 0 4px',
  },
  brand: {
    color: p.brand,
    fontFamily: 'Arial, Helvetica, sans-serif',
    fontWeight: 900,
    fontSize: 18,
    letterSpacing: 4,
    textShadow: '0 1px 0 rgba(0,0,0,0.6)',
  },
  screenBezel: {
    background: p.shellDark,
    borderRadius: 10,
    padding: 10,
    boxShadow: [
      'inset 0 2px 6px rgba(0,0,0,0.7)',
      'inset 0 0 0 1px #000',
      '0 1px 0 rgba(255,255,255,0.05)',
    ].join(', '),
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
  },
  canvasLeaderboardOverlay: {
    position: 'absolute',
    inset: 0,
    display: 'flex',
    flexDirection: 'column',
    padding: 10,
    background: p.canvasBg,
    color: p.canvasFg,
    boxSizing: 'border-box',
    overflow: 'hidden',
  },
  scoreboard: {
    background: p.canvasBg,
    color: p.canvasFg,
    borderRadius: 4,
    padding: '6px 10px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    fontWeight: 700,
    letterSpacing: 1,
    boxShadow: 'inset 0 0 0 1px rgba(0,0,0,0.35)',
  },
  scoreItem: { display: 'flex', flexDirection: 'column', alignItems: 'center' },
  scoreLabel: { fontSize: 9, opacity: 0.7, letterSpacing: 2 },
  scoreValue: { fontSize: 18 },
  modeBadge: {
    fontSize: 10,
    padding: '2px 8px',
    borderRadius: 2,
    background: p.canvasFg,
    color: p.canvasBg,
    letterSpacing: 1,
  },
  canvasFrame: {
    background: p.canvasBg,
    padding: 6,
    borderRadius: 4,
    boxShadow: 'inset 0 0 0 1px rgba(0,0,0,0.35)',
    width: '100%',
    aspectRatio: '1 / 1',
    position: 'relative',
  },
  canvas: {
    width: '100%',
    height: '100%',
    display: 'block',
    imageRendering: 'pixelated',
  },
  controlsRow: {
    display: 'flex',
    gap: 6,
    flexWrap: 'wrap',
    justifyContent: 'center',
  },
  btn: {
    flex: '1 1 90px',
    padding: '10px 12px',
    background: `linear-gradient(180deg, ${p.shellLight} 0%, ${p.key} 100%)`,
    color: p.keyText,
    border: '1px solid #000',
    borderRadius: 8,
    fontWeight: 700,
    letterSpacing: 1,
    cursor: 'pointer',
    fontFamily: 'inherit',
    textTransform: 'uppercase',
    fontSize: 12,
    boxShadow: [
      'inset 0 1px 0 rgba(255,255,255,0.15)',
      'inset 0 -2px 0 rgba(0,0,0,0.45)',
      '0 1px 0 rgba(0,0,0,0.5)',
    ].join(', '),
  },
  btnGhost: {
    flex: '1 1 90px',
    padding: '10px 12px',
    background: 'transparent',
    color: p.keyText,
    border: `1px solid ${p.keyText}`,
    borderRadius: 8,
    fontWeight: 700,
    letterSpacing: 1,
    cursor: 'pointer',
    fontFamily: 'inherit',
    textTransform: 'uppercase',
    fontSize: 12,
    opacity: 0.85,
  },
  dpadWrap: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, 60px)',
    gridTemplateRows: 'repeat(3, 60px)',
    gap: 4,
    justifyContent: 'center',
    marginTop: 4,
    userSelect: 'none',
  },
  dpadBtn: {
    background: `linear-gradient(180deg, ${p.shellLight} 0%, ${p.key} 100%)`,
    color: p.keyText,
    border: '1px solid #000',
    borderRadius: 10,
    fontSize: 20,
    fontWeight: 900,
    cursor: 'pointer',
    touchAction: 'manipulation',
    fontFamily: 'inherit',
    boxShadow: [
      'inset 0 1px 0 rgba(255,255,255,0.18)',
      'inset 0 -3px 0 rgba(0,0,0,0.5)',
      '0 1px 0 rgba(0,0,0,0.6)',
    ].join(', '),
  },
  dpadCenter: {
    background:
      'radial-gradient(circle at 35% 30%, #e6e3d6 0%, #9c9886 70%, #6c6857 100%)',
    color: p.shellDark,
    border: '1px solid #000',
    borderRadius: 12,
    fontSize: 18,
    fontWeight: 900,
    cursor: 'pointer',
    touchAction: 'manipulation',
    fontFamily: 'inherit',
    boxShadow: [
      'inset 0 1px 0 rgba(255,255,255,0.5)',
      'inset 0 -2px 0 rgba(0,0,0,0.35)',
      '0 1px 0 rgba(0,0,0,0.6)',
    ].join(', '),
  },
  footer: {
    fontSize: 10,
    opacity: 0.55,
    textAlign: 'center',
    marginTop: 6,
    letterSpacing: 1,
    color: p.keyText,
  },
  leaderboard: {
    background: p.canvasBg,
    color: p.canvasFg,
    borderRadius: 4,
    padding: '8px 10px',
    boxShadow: 'inset 0 0 0 1px rgba(0,0,0,0.35)',
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
  },
  leaderboardTitle: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: 2,
    textAlign: 'center',
    opacity: 0.85,
  },
  leaderboardEmpty: {
    fontSize: 10,
    textAlign: 'center',
    opacity: 0.6,
    padding: '4px 0',
  },
  leaderboardList: {
    listStyle: 'none',
    margin: 0,
    padding: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: 1,
  },
  leaderboardRow: {
    display: 'grid',
    gridTemplateColumns: '24px 1fr auto',
    alignItems: 'center',
    fontSize: 12,
    fontWeight: 700,
    letterSpacing: 1,
    padding: '1px 0',
  },
  leaderboardRank: { opacity: 0.7 },
  leaderboardName: { textTransform: 'uppercase' },
  leaderboardScore: { fontVariantNumeric: 'tabular-nums' },
  modalOverlay: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(7, 9, 13, 0.75)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
    zIndex: 50,
  },
  modalCard: {
    width: '100%',
    maxWidth: 300,
    background: p.modalBg,
    color: p.modalFg,
    borderRadius: 6,
    padding: 16,
    border: `2px solid ${p.modalBorder}`,
    boxShadow: [
      '0 12px 30px rgba(0,0,0,0.55)',
      'inset 0 0 0 1px rgba(0,0,0,0.35)',
    ].join(', '),
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
    fontFamily: 'ui-monospace, SFMono-Regular, Menlo, Consolas, monospace',
  },
  modalTitle: {
    fontSize: 12,
    fontWeight: 800,
    letterSpacing: 2,
    textAlign: 'center',
  },
  modalScore: {
    fontSize: 36,
    fontWeight: 900,
    textAlign: 'center',
    lineHeight: 1,
    fontVariantNumeric: 'tabular-nums',
  },
  modalSubtitle: {
    fontSize: 11,
    letterSpacing: 1,
    textAlign: 'center',
    opacity: 0.75,
  },
  modalInput: {
    width: '100%',
    boxSizing: 'border-box',
    padding: '8px 10px',
    fontSize: 16,
    fontWeight: 700,
    letterSpacing: 2,
    textTransform: 'uppercase',
    textAlign: 'center',
    fontFamily: 'inherit',
    background: p.modalInputBg,
    color: p.modalFg,
    border: `1px solid ${p.modalBorder}`,
    borderRadius: 4,
    outline: 'none',
  },
  modalActions: {
    display: 'flex',
    gap: 8,
    marginTop: 4,
  },
});
